#*Using Apriori Algorithm*

In [38]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori, association_rules
from apyori import apriori

In [26]:
!pip install apyori

Requirement already satisfied: apyori in /usr/local/lib/python3.7/dist-packages (1.1.2)

In [33]:
df = pd.read_csv('/content/GroceryStoreDataSet.csv', names = ['products'], sep = ',')
df

                          products
0               MILK,BREAD,BISCUIT
1    BREAD,MILK,BISCUIT,CORNFLAKES
2              BREAD,TEA,BOURNVITA
3             JAM,MAGGI,BREAD,MILK
4                MAGGI,TEA,BISCUIT
5              BREAD,TEA,BOURNVITA
6             MAGGI,TEA,CORNFLAKES
7          MAGGI,BREAD,TEA,BISCUIT
8              JAM,MAGGI,BREAD,TEA
9                       BREAD,MILK
10  COFFEE,COCK,BISCUIT,CORNFLAKES
11  COFFEE,COCK,BISCUIT,CORNFLAKES
12          COFFEE,SUGER,BOURNVITA
13               BREAD,COFFEE,COCK
14             BREAD,SUGER,BISCUIT
15         COFFEE,SUGER,CORNFLAKES
16           BREAD,SUGER,BOURNVITA
17              BREAD,COFFEE,SUGER
18              BREAD,COFFEE,SUGER
19      TEA,MILK,COFFEE,CORNFLAKES

In [34]:
df.head()

                        products
0             MILK,BREAD,BISCUIT
1  BREAD,MILK,BISCUIT,CORNFLAKES
2            BREAD,TEA,BOURNVITA
3           JAM,MAGGI,BREAD,MILK
4              MAGGI,TEA,BISCUIT

In [35]:
df.tail()

                      products
15     COFFEE,SUGER,CORNFLAKES
16       BREAD,SUGER,BOURNVITA
17          BREAD,COFFEE,SUGER
18          BREAD,COFFEE,SUGER
19  TEA,MILK,COFFEE,CORNFLAKES

In [3]:
df.shape

(20, 1)

In [4]:
#Splitting the dataset
data = list(df["products"].apply(lambda x:x.split(",") ))
data

[['MILK', 'BREAD', 'BISCUIT'],
 ['BREAD', 'MILK', 'BISCUIT', 'CORNFLAKES'],
 ['BREAD', 'TEA', 'BOURNVITA'],
 ['JAM', 'MAGGI', 'BREAD', 'MILK'],
 ['MAGGI', 'TEA', 'BISCUIT'],
 ['BREAD', 'TEA', 'BOURNVITA'],
 ['MAGGI', 'TEA', 'CORNFLAKES'],
 ['MAGGI', 'BREAD', 'TEA', 'BISCUIT'],
 ['JAM', 'MAGGI', 'BREAD', 'TEA'],
 ['BREAD', 'MILK'],
 ['COFFEE', 'COCK', 'BISCUIT', 'CORNFLAKES'],
 ['COFFEE', 'COCK', 'BISCUIT', 'CORNFLAKES'],
 ['COFFEE', 'SUGER', 'BOURNVITA'],
 ['BREAD', 'COFFEE', 'COCK'],
 ['BREAD', 'SUGER', 'BISCUIT'],
 ['COFFEE', 'SUGER', 'CORNFLAKES'],
 ['BREAD', 'SUGER', 'BOURNVITA'],
 ['BREAD', 'COFFEE', 'SUGER'],
 ['BREAD', 'COFFEE', 'SUGER'],
 ['TEA', 'MILK', 'COFFEE', 'CORNFLAKES']]

In [5]:
#Let's transform the list, with one-hot encoding 
from mlxtend.preprocessing import TransactionEncoder
a = TransactionEncoder()
a_data = a.fit(data).transform(data)
df = pd.DataFrame(a_data,columns=a.columns_)
df = df.replace(False,0)
df

    BISCUIT  BOURNVITA  BREAD  COCK  COFFEE  ...  JAM  MAGGI  MILK  SUGER  TEA
0       1.0        0.0    1.0   0.0     0.0  ...  0.0    0.0   1.0    0.0  0.0
1       1.0        0.0    1.0   0.0     0.0  ...  0.0    0.0   1.0    0.0  0.0
2       0.0        1.0    1.0   0.0     0.0  ...  0.0    0.0   0.0    0.0  1.0
3       0.0        0.0    1.0   0.0     0.0  ...  1.0    1.0   1.0    0.0  0.0
4       1.0        0.0    0.0   0.0     0.0  ...  0.0    1.0   0.0    0.0  1.0
5       0.0        1.0    1.0   0.0     0.0  ...  0.0    0.0   0.0    0.0  1.0
6       0.0        0.0    0.0   0.0     0.0  ...  0.0    1.0   0.0    0.0  1.0
7       1.0        0.0    1.0   0.0     0.0  ...  0.0    1.0   0.0    0.0  1.0
8       0.0        0.0    1.0   0.0     0.0  ...  1.0    1.0   0.0    0.0  1.0
9       0.0        0.0    1.0   0.0     0.0  ...  0.0    0.0   1.0    0.0  0.0
10      1.0        0.0    0.0   1.0     1.0  ...  0.0    0.0   0.0    0.0  0.0
11      1.0        0.0    0.0   1.0     1.0  ...  0.0    0.0   0.0    0.0  0.0
12      0.0        1.0    0.0   0.0     1.0  ...  0.0    0.0   0.0    1.0  0.0
13      0.0        0.0    1.0   1.0     1.0  ...  0.0    0.0   0.0    0.0  0.0
14      1.0        0.0    1.0   0.0     0.0  ...  0.0    0.0   0.0    1.0  0.0
15      0.0        0.0    0.0   0.0     1.0  ...  0.0    0.0   0.0    1.0  0.0
16      0.0        1.0    1.0   0.0     0.0  ...  0.0    0.0   0.0    1.0  0.0
17      0.0        0.0    1.0   0.0     1.0  ...  0.0    0.0   0.0    1.0  0.0
18      0.0        0.0    1.0   0.0     1.0  ...  0.0    0.0   0.0    1.0  0.0
19      0.0        0.0    0.0   0.0     1.0  ...  0.0    0.0   1.0    0.0  1.0

[20 rows x 11 columns]

In [48]:
#set a threshold value for the support value and calculate the support value.
df = apriori(df, min_support = 0.2, use_colnames = True, verbose = 1)
df

In [ ]:
#Let's view our interpretation values using the Associan rule function.
df_ar = association_rules(df, metric = "confidence", min_threshold = 0.6)
df_ar